---
title: "Synthetic Controls"
date: 'Report generated `r format(Sys.time(), "%A, %B %d, %Y")`'
knit: (function(inputFile, encoding) { 
      country <<- 'SC_Dec/Coverage groups';
      out_dir <- paste(paste('~/Documents/Synthetic Control Data/', country, '/', sep = ''), 'results', sep = '');
      rmarkdown::render(inputFile,
                        encoding = encoding, 
                        output_file = file.path(out_dir, 'analysis.html')) })
output:
 html_document:
  toc: TRUE
  toc_float: TRUE
---

```{r setup, include = FALSE}
library('parallel', quietly = TRUE)
library('splines', quietly = TRUE)
library('lubridate', quietly = TRUE)
library('CausalImpact', quietly = TRUE)
library('zoo', quietly = TRUE)
knitr::opts_chunk$set(echo = FALSE)
```

```{r analysis, include = FALSE}
source('~/GitHub/synthetic-control/synthetic_control_analysis_function.R')
original_country <- country
results <- syntheticControl(country = country, use_defaults = TRUE)
country <- gsub('/', '_', country)
```

#`r country` Results

```{r sparse}
if (!is.null(names(results$sparse_groups[results$sparse_groups])) && length(names(results$sparse_groups[results$sparse_groups])) != 0) {
	knitr::kable(data.frame('Sparse Groups' = names(results$sparse_groups[results$sparse_groups]), check.names = FALSE), align = 'c')
}
```

##ITS
```{r ITS}
knitr::kable(results$rr_mean_time, align = 'c')
```

##Synthetic Controls
```{r SC}
knitr::kable(results$rr_mean_full, align = 'c')
```

##No Covariates
```{r none}
knitr::kable(results$rr_mean_none, align = 'c')
```

##Inclusion Probabilities
```{r incl, include = FALSE}
incl_probs <- NULL
for (age_group in results$groups) {
	incl_prob <- rev(plot(results$impact_full[[age_group]]$model$bsts.model, 'coefficients')$inclusion.prob)[1:3]
	incl_prob <- data.frame('Group' = age_group, 'Greatest Inclusion Variable' = names(incl_prob)[1], 'Greatest Inclusion Probability' = incl_prob[1], 'Second Greatest Inclusion Variable' = names(incl_prob)[2], 'Second Greatest Inclusion Probability' = incl_prob[2], 'Third Greatest Inclusion Variable' = names(incl_prob)[3], 'Third Greatest Inclusion Probability' = incl_prob[3], check.names = FALSE)
	incl_probs <- rbind(incl_probs, incl_prob)
}
rownames(incl_probs) <- NULL
```

```{r incl_table}
knitr::kable(incl_probs, align = 'c')
```

##Weight Sensitivity Analysis
```{r sensitivity}
knitr::kable(results$sensitivity_table, align = 'c')
```

##Pred Sensitivity Analysis
```{r pred_sensitivity}
knitr::kable(results$pred_sensitivity$pred_2, align = 'c', caption = 'n_pred = 2')
knitr::kable(results$pred_sensitivity$pred_10, align = 'c', caption = 'n_pred = 10')
```

##Plots
```{r plots, results = 'asis'}
for (group in results$groups) {
	cat('###', group, '\n', sep = '')
	plotPred(results$pred_quantiles_full[, , group], results$time_points, results$post_period, results$pred_quantiles_full[, , group], results$outcome_plot[, group], country, title = paste(group, 'Synthetic controls estimate'))
	plotPred(results$pred_quantiles_time[, , group], results$time_points, results$post_period, results$pred_quantiles_full[, , group], results$outcome_plot[, group], country, title = paste(group, 'Interupted time series estimate'))
	plotPred(results$pred_quantiles_none[, , group], results$time_points, results$post_period, results$pred_quantiles_full[, , group], results$outcome_plot[, group], country, title = paste(group, 'No covariates estimate'))
	cat('\n\n')
}
```